// Generated by gencpp from file lesson_move_group/sensor_accessor.msg
// DO NOT EDIT!


#ifndef LESSON_MOVE_GROUP_MESSAGE_SENSOR_ACCESSOR_H
#define LESSON_MOVE_GROUP_MESSAGE_SENSOR_ACCESSOR_H

#include <ros/service_traits.h>


#include <lesson_move_group/sensor_accessorRequest.h>
#include <lesson_move_group/sensor_accessorResponse.h>


namespace lesson_move_group
{

struct sensor_accessor
{

typedef sensor_accessorRequest Request;
typedef sensor_accessorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sensor_accessor
} // namespace lesson_move_group


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lesson_move_group::sensor_accessor > {
  static const char* value()
  {
    return "c8c699ce907261a9c404410e16c0ef0d";
  }

  static const char* value(const ::lesson_move_group::sensor_accessor&) { return value(); }
};

template<>
struct DataType< ::lesson_move_group::sensor_accessor > {
  static const char* value()
  {
    return "lesson_move_group/sensor_accessor";
  }

  static const char* value(const ::lesson_move_group::sensor_accessor&) { return value(); }
};


// service_traits::MD5Sum< ::lesson_move_group::sensor_accessorRequest> should match 
// service_traits::MD5Sum< ::lesson_move_group::sensor_accessor > 
template<>
struct MD5Sum< ::lesson_move_group::sensor_accessorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lesson_move_group::sensor_accessor >::value();
  }
  static const char* value(const ::lesson_move_group::sensor_accessorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lesson_move_group::sensor_accessorRequest> should match 
// service_traits::DataType< ::lesson_move_group::sensor_accessor > 
template<>
struct DataType< ::lesson_move_group::sensor_accessorRequest>
{
  static const char* value()
  {
    return DataType< ::lesson_move_group::sensor_accessor >::value();
  }
  static const char* value(const ::lesson_move_group::sensor_accessorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lesson_move_group::sensor_accessorResponse> should match 
// service_traits::MD5Sum< ::lesson_move_group::sensor_accessor > 
template<>
struct MD5Sum< ::lesson_move_group::sensor_accessorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lesson_move_group::sensor_accessor >::value();
  }
  static const char* value(const ::lesson_move_group::sensor_accessorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lesson_move_group::sensor_accessorResponse> should match 
// service_traits::DataType< ::lesson_move_group::sensor_accessor > 
template<>
struct DataType< ::lesson_move_group::sensor_accessorResponse>
{
  static const char* value()
  {
    return DataType< ::lesson_move_group::sensor_accessor >::value();
  }
  static const char* value(const ::lesson_move_group::sensor_accessorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LESSON_MOVE_GROUP_MESSAGE_SENSOR_ACCESSOR_H
